services:
  - type: web
    name: moneymind-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 8000
    healthCheckPath: /
    autoDeploy: true